# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary/CMakeFiles /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gatorLibrary

# Build rule for target.
gatorLibrary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gatorLibrary
.PHONY : gatorLibrary

# fast build rule for target.
gatorLibrary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/build
.PHONY : gatorLibrary/fast

book.o: book.cpp.o
.PHONY : book.o

# target to build an object file
book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/book.cpp.o
.PHONY : book.cpp.o

book.i: book.cpp.i
.PHONY : book.i

# target to preprocess a source file
book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/book.cpp.i
.PHONY : book.cpp.i

book.s: book.cpp.s
.PHONY : book.s

# target to generate assembly for a file
book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/book.cpp.s
.PHONY : book.cpp.s

gator_library.o: gator_library.cpp.o
.PHONY : gator_library.o

# target to build an object file
gator_library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/gator_library.cpp.o
.PHONY : gator_library.cpp.o

gator_library.i: gator_library.cpp.i
.PHONY : gator_library.i

# target to preprocess a source file
gator_library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/gator_library.cpp.i
.PHONY : gator_library.cpp.i

gator_library.s: gator_library.cpp.s
.PHONY : gator_library.s

# target to generate assembly for a file
gator_library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/gator_library.cpp.s
.PHONY : gator_library.cpp.s

gl_input.o: gl_input.cpp.o
.PHONY : gl_input.o

# target to build an object file
gl_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/gl_input.cpp.o
.PHONY : gl_input.cpp.o

gl_input.i: gl_input.cpp.i
.PHONY : gl_input.i

# target to preprocess a source file
gl_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/gl_input.cpp.i
.PHONY : gl_input.cpp.i

gl_input.s: gl_input.cpp.s
.PHONY : gl_input.s

# target to generate assembly for a file
gl_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/gl_input.cpp.s
.PHONY : gl_input.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/main.cpp.s
.PHONY : main.cpp.s

redblack_tree.o: redblack_tree.cpp.o
.PHONY : redblack_tree.o

# target to build an object file
redblack_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/redblack_tree.cpp.o
.PHONY : redblack_tree.cpp.o

redblack_tree.i: redblack_tree.cpp.i
.PHONY : redblack_tree.i

# target to preprocess a source file
redblack_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/redblack_tree.cpp.i
.PHONY : redblack_tree.cpp.i

redblack_tree.s: redblack_tree.cpp.s
.PHONY : redblack_tree.s

# target to generate assembly for a file
redblack_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/redblack_tree.cpp.s
.PHONY : redblack_tree.cpp.s

reservation.o: reservation.cpp.o
.PHONY : reservation.o

# target to build an object file
reservation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/reservation.cpp.o
.PHONY : reservation.cpp.o

reservation.i: reservation.cpp.i
.PHONY : reservation.i

# target to preprocess a source file
reservation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/reservation.cpp.i
.PHONY : reservation.cpp.i

reservation.s: reservation.cpp.s
.PHONY : reservation.s

# target to generate assembly for a file
reservation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gatorLibrary.dir/build.make CMakeFiles/gatorLibrary.dir/reservation.cpp.s
.PHONY : reservation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gatorLibrary"
	@echo "... book.o"
	@echo "... book.i"
	@echo "... book.s"
	@echo "... gator_library.o"
	@echo "... gator_library.i"
	@echo "... gator_library.s"
	@echo "... gl_input.o"
	@echo "... gl_input.i"
	@echo "... gl_input.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... redblack_tree.o"
	@echo "... redblack_tree.i"
	@echo "... redblack_tree.s"
	@echo "... reservation.o"
	@echo "... reservation.i"
	@echo "... reservation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

