# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary/CMakeFiles /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kkeshav/Desktop/UFL/courses/fall24/ads/GatorLibrary/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GatorLibrary

# Build rule for target.
GatorLibrary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GatorLibrary
.PHONY : GatorLibrary

# fast build rule for target.
GatorLibrary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/build
.PHONY : GatorLibrary/fast

GatorLibrary.o: GatorLibrary.cpp.o
.PHONY : GatorLibrary.o

# target to build an object file
GatorLibrary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/GatorLibrary.cpp.o
.PHONY : GatorLibrary.cpp.o

GatorLibrary.i: GatorLibrary.cpp.i
.PHONY : GatorLibrary.i

# target to preprocess a source file
GatorLibrary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/GatorLibrary.cpp.i
.PHONY : GatorLibrary.cpp.i

GatorLibrary.s: GatorLibrary.cpp.s
.PHONY : GatorLibrary.s

# target to generate assembly for a file
GatorLibrary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/GatorLibrary.cpp.s
.PHONY : GatorLibrary.cpp.s

book.o: book.cpp.o
.PHONY : book.o

# target to build an object file
book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/book.cpp.o
.PHONY : book.cpp.o

book.i: book.cpp.i
.PHONY : book.i

# target to preprocess a source file
book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/book.cpp.i
.PHONY : book.cpp.i

book.s: book.cpp.s
.PHONY : book.s

# target to generate assembly for a file
book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/book.cpp.s
.PHONY : book.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/main.cpp.s
.PHONY : main.cpp.s

redblacktree.o: redblacktree.cpp.o
.PHONY : redblacktree.o

# target to build an object file
redblacktree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/redblacktree.cpp.o
.PHONY : redblacktree.cpp.o

redblacktree.i: redblacktree.cpp.i
.PHONY : redblacktree.i

# target to preprocess a source file
redblacktree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/redblacktree.cpp.i
.PHONY : redblacktree.cpp.i

redblacktree.s: redblacktree.cpp.s
.PHONY : redblacktree.s

# target to generate assembly for a file
redblacktree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GatorLibrary.dir/build.make CMakeFiles/GatorLibrary.dir/redblacktree.cpp.s
.PHONY : redblacktree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GatorLibrary"
	@echo "... GatorLibrary.o"
	@echo "... GatorLibrary.i"
	@echo "... GatorLibrary.s"
	@echo "... book.o"
	@echo "... book.i"
	@echo "... book.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... redblacktree.o"
	@echo "... redblacktree.i"
	@echo "... redblacktree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

